### ISSUE TITLE
TX power PAtable

### ISSUE THREAD

**Issue by sanderkob** [mrfaptastic/Easy-ESP-IoT-Arduino-CC1101-LORA#2]
The library is easy to use, but  I cannot program the PAtable (single byte) in register 0x3E, so have to work with low TX power. Any attempt to program that register upsets the CC1101. Working with ESP8266 (WEMOS D1 lite). Any ideas?

**Comment by mrfaptastic** [comment]
Thanks for your feedback. Glad it works.

I will take a look at it over the weekend. I didn't actually spend much
time on the PA table bit but I'll see what I can do.

Can you provide the PA table values you're looking to set?

Thanks

**Comment by sanderkob** [comment]
I am looking for more transmitting power, max. value for 868 MHz would be
0xC0 or 0xC2 (just one value, in PAtable[0], FREND0 = 10). Reading or
writing to address 0x3E upsets the CC1101, lowering the D1 clock from 160
Mhz to 80 MHz does not help.
By the way, I found that when you do only one mode (I think RX) you do need
the lines 515-518 to send an empty packet (it was commented out).

Op do 27 jun. 2019 19:23 schreef mrfaptastic <notifications@github.com>:

**Comment by sanderkob** [comment]
Issue solved, it turns out the value was correctly written into the PAtable, but I coult not read back that register. I checked that the RSSI changes according to the programmed value in PAtable[0].

**Comment by mrfaptastic** [comment]
Good to hear. Are your able the provide the code you used to read the PA
status table without the cc1101 playing up?

I'll add this into the library, similar to the printCConfigCheck function
to aid future debugging.

**Comment by sanderkob** [comment]
Sorry, I could not read te PA status table. SInce  the RSSI follows the programmed PA setting, my conclusion that programming the PA table works.

**Comment by mrfaptastic** [comment]
Hi, I added a function to be able to change to TX power and also one to be able to print the PATables: printPATable()
